 
```{r include=FALSE}
library(imputeTS)
library(knitr)
library(dplyr)
library(flextable)
library(magrittr)
library(kableExtra)
library(tidytext)
library(tidyverse)
library(plot.matrix)
library(stringr)
library(ggpubr)
library(highcharter)
library(ggpubr)
library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(viridisLite)
library(Rtsne)
library(qvalue)
library(jaccard)
library(lsa)
library(patchwork)
library(plotly)
```

```{r}
load('test.RData')
```


```{r}
library(plotly)
library(lattice) 

# volcano is a numeric matrix that ships with R

f = function(x1,x2){
  b0 = beta_h[1]
  b1 = beta_h[2]
  b2 = beta_h[3]
  return(b0+b1*x1+b2*x2)
}
#z = rbind(x, x+y)
#wireframe(z ~ x + y, xlab="Parameter 1", ylab="Parameter 2", zlab="Fitness Value")
z <- outer(X = x1,Y = x2,FUN = f)

fig <- plot_ly(x=x1,y=x2,z=t(z))
fig <- fig %>% add_surface()

fig = plot_ly(x=x1, y=x2, z=t(z), type = "surface") %>% 
  add_trace(data = data_model, 
            x = x1, 
            y = x2, 
            z = y, 
            mode = "markers", 
            type = "scatter3d", 
            marker = list(size = 5, color = "red", symbol = 104))


fig
```

```{r}
data_model = as.data.frame(cbind(y,x1,x2))
linear_model = lm(y~., data = data_model)
```

```{r}
summary(linear_model)
```

```{r}
#correlation coefficient
n = 500
c_x1 = (n*sum(x1*y)-sum(x1)*sum(y))/(sqrt(n*sum(x1^2)-(sum(x1))^2)*sqrt(n*sum(y^2)-(sum(y))^2))

c_x2 = (n*sum(x2*y)-sum(x2)*sum(y))/(sqrt(n*sum(x2^2)-(sum(x2))^2)*sqrt(n*sum(y^2)-(sum(y))^2))
```

```{r}
r_x1 = (sum((x1-mean(x1))*(y-mean(y))))/sqrt(sum(((x1-mean(x1))^2*(y-mean(y))^2)))
r_x2 = (sum((x2-mean(x2))*(y-mean(y))))/sqrt(sum(((x2-mean(x2))^2*(y-mean(y))^2)))
```

# LSE of $\beta_1$

* $\hat{\beta_1} = (\mathbb{X}'\mathbb{X})^{-1}\mathbb{X}'\mathbb{Y}$

```{r}
X = as.matrix(cbind(rep(1,500), x1,x2))
Y = matrix(y, nrow = 500, ncol = 1)

beta_h = solve(t(X)%*%X)%*%t(X)%*%Y
beta_h
```

# t-test 
```{r}
beta1 = (Y-beta_h[1]-beta_h[3]*x2)/x1
t.test(beta1, mu = 2, alternative = 'greater')
```